In [1]:
import numpy as np

l1 = [1,2,3]
l2 = [4,5,6]

A1 = np.array(l1)
A2 = np.array(l2)

print(f"{A1} * {A2} = {A1*A2}")

[1 2 3] * [4 5 6] = [ 4 10 18]

In [2]:
import numpy as np

l1 = [1,2,3]
l2 = [4,5,6]

A1 = np.array(l1)
A2 = np.array(l2)

A = A1*A2

print(f"{A1} * {A2} = {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

[1 2 3] * [4 5 6] = [ 4 10 18]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int64
The dimension of an array: (3,)

In [3]:
import numpy as np

l1 = [1,2,3]
l2 = [4,5,6]

A1 = np.array(l1, np.int8)
A2 = np.array(l2, np.int8)

A = A1*A2

print(f"{A1} * {A2} = {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

[1 2 3] * [4 5 6] = [ 4 10 18]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int8
The dimension of an array: (3,)

In [4]:
import numpy as np

l1 = [1,2,3]
l2 = [4,5,6]

A1 = np.array(l1, np.int8)
A2 = np.array(l2, np.int8)

A = A1*A2

print(f"{A1} * {A2} = {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

[1 2 3] * [4 5 6] = [ 4 10 18]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int8
The dimension of an array: (3,)
The size of an array: 3

In [5]:
import numpy as np

l1 = [1,2,3]
l2 = [4,5,6]

A = np.array((l1, l2))
print(f" The 2D array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

 The 2D array is :
 [[1 2 3]
 [4 5 6]]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int64
The dimension of an array: (2, 3)
The size of an array: 6

In [6]:
A = np.array(([1,2,3,4,5]))
print(f" The 1D array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

 The 1D array is :
 [1 2 3 4 5]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int64
The dimension of an array: (5,)
The size of an array: 5

In [7]:
import numpy as np

A = np.array(([1,2,3,4,5], [2,3,4,5,6]))
print(f" The 2D array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

 The 2D array is :
 [[1 2 3 4 5]
 [2 3 4 5 6]]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int64
The dimension of an array: (2, 5)
The size of an array: 10

In [8]:
import numpy as np

r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]

A = np.array((r1,r2,r3,r4))
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

 The array is :
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int64
The dimension of an array: (4, 4)
The size of an array: 16

In [9]:
import numpy as np

r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]

A = np.array((r1,r2,r3,r4))
print(f" The original array is : \n {A}")

A[1,2] = 10
print(f" The array after replacing : \n {A}")

 The original array is :
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
 The array after replacing :
 [[ 1  2  3  4]
 [ 3  6 10  4]
 [ 1  2  9  4]
 [ 1  4  5  4]]

In [10]:
import numpy as np

A = np.zeros([5,5])
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

 The array is :
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: float64
The dimension of an array: (5, 5)
The size of an array: 25

In [11]:
import numpy as np

A = np.zeros([5])
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

 The array is :
 [0. 0. 0. 0. 0.]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: float64
The dimension of an array: (5,)
The size of an array: 5

In [12]:
import numpy as np

A = np.arange(1,100)
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

 The array is :
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int64
The dimension of an array: (99,)
The size of an array: 99

In [13]:
import numpy as np

A = np.arange(1,100,10)
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

 The array is :
 [ 1 11 21 31 41 51 61 71 81 91]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int64
The dimension of an array: (10,)
The size of an array: 10

In [14]:
import numpy as np

A = np.linspace(2,3,100)
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

 The array is :
 [2.         2.01010101 2.02020202 2.03030303 2.04040404 2.05050505
 2.06060606 2.07070707 2.08080808 2.09090909 2.1010101  2.11111111
 2.12121212 2.13131313 2.14141414 2.15151515 2.16161616 2.17171717
 2.18181818 2.19191919 2.2020202  2.21212121 2.22222222 2.23232323
 2.24242424 2.25252525 2.26262626 2.27272727 2.28282828 2.29292929
 2.3030303  2.31313131 2.32323232 2.33333333 2.34343434 2.35353535
 2.36363636 2.37373737 2.38383838 2.39393939 2.4040404  2.41414141
 2.42424242 2.43434343 2.44444444 2.45454545 2.46464646 2.47474747
 2.48484848 2.49494949 2.50505051 2.51515152 2.52525253 2.53535354
 2.54545455 2.55555556 2.56565657 2.57575758 2.58585859 2.5959596
 2.60606061 2.61616162 2.62626263 2.63636364 2.64646465 2.65656566
 2.66666667 2.67676768 2.68686869 2.6969697  2.70707071 2.71717172
 2.72727273 2.73737374 2.74747475 2.75757576 2.76767677 2.77777778
 2.78787879 2.7979798  2.80808081 2.81818182 2.82828283 2.83838384
 2.84848485 2.85858586 2.86868687 2.87878788 2.88888889 2.8989899
 2.90909091 2.91919192 2.92929293 2.93939394 2.94949495 2.95959596
 2.96969697 2.97979798 2.98989899 3.        ]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: float64
The dimension of an array: (100,)
The size of an array: 100

In [15]:
import numpy as np

A = np.identity(5)
print(f" The array is : \n {A}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

 The array is :
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: float64
The dimension of an array: (5, 5)
The size of an array: 25

In [16]:
import numpy as np

r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]

A = np.array((r1,r2,r3,r4))
print(f" The Matrix is : \n {A}")

print(f" The row wise sum is : {A.sum(axis=1)}")
print(f" The column wise sum is : {A.sum(axis=0)}")

print(f"The type of array using type: {type(A)}")
print(f"The type of array using dtype: {A.dtype}") # no () with dtype because it is an attribute of A not a function

print(f"The dimension of an array: {A.shape}")

print(f"The size of an array: {A.size}") # The size attrubute counts the total element in the array

 The Matrix is :
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
 The row wise sum is : [10 16 16 14]
 The column wise sum is : [ 6 14 20 16]
The type of array using type: <class 'numpy.ndarray'>
The type of array using dtype: int64
The dimension of an array: (4, 4)
The size of an array: 16

In [17]:
import numpy as np

r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]

A = np.array((r1,r2,r3,r4))
print(f" The Matrix is : \n {A}")

print(f" The transpose is : \n {A.T}")

 The Matrix is :
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
 The transpose is :
 [[1 3 1 1]
 [2 6 2 4]
 [3 3 9 5]
 [4 4 4 4]]

In [18]:
import numpy as np

r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]

A = np.array((r1,r2,r3,r4))
print(f" The 4x4 Matrix is : \n {A}")

print(f" The 8x2 matrix: \n {A.reshape(8,2)}")

 The 4x4 Matrix is :
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
 The 8x2 matrix:
 [[1 2]
 [3 4]
 [3 6]
 [3 4]
 [1 2]
 [9 4]
 [1 4]
 [5 4]]

In [20]:
import numpy as np

r1 = [1,2,3,4]
r2 = [3,6,3,4]
r3 = [1,2,9,4]
r4 = [1,4,5,4]

A = np.array((r1,r2,r3,r4))
print(f" The 4x4 Matrix is : \n {A}")

print(f" The 1D array from above matrix using ravel: \n {A.ravel()}")

 The 4x4 Matrix is :
 [[1 2 3 4]
 [3 6 3 4]
 [1 2 9 4]
 [1 4 5 4]]
 The 1D array from above matrix using ravel:
 [1 2 3 4 3 6 3 4 1 2 9 4 1 4 5 4]

In [21]:
import numpy as np

a = [1, 16, 31, 4]

A = np.array(a)
print(f"The original array: {A}")

print(f"The index of maximum value in array is: {A.argmax()}")
print(f"The index of minimum value in array is: {A.argmin()}")
print(f"Sorted Indexes: {A.argsort()}")

The original array: [ 1 16 31  4]
The index of maximum value in array is: 2
The index of minimum value in array is: 0
Sorted Indexes: [0 3 1 2]

In [22]:
import numpy as np

f1=np.full((2,2),5)
f1

array([[5, 5],
       [5, 5]])

In [23]:
f2 = np.full((2,2), 3)
f2

array([[3, 3],
       [3, 3]])

In [24]:
a = np.vstack([f1, f2])
a

array([[5, 5],
       [5, 5],
       [3, 3],
       [3, 3]])

In [25]:
b = np.hstack([f1, f2])
b

array([[5, 5, 3, 3],
       [5, 5, 3, 3]])

In [26]:
a = np.column_stack([f1, f2])
a

array([[5, 5, 3, 3],
       [5, 5, 3, 3]])

In [27]:
import numpy as np

a = np.full((2,3), 5)
a

array([[5, 5, 5],
       [5, 5, 5]])

In [28]:
np.save("untitled.npy", a)

In [29]:
savedMatrix = np.load('untitled.npy')
savedMatrix

array([[5, 5, 5],
       [5, 5, 5]])

In [30]:
import numpy as np

f1=np. full((2,2),5)
print("\nf1 = \n",f1)

f2=np.full((2,2), 3)
print("\nf2 = \n", f2)

print("point to point multiplication = ",f1*f2)

print("point to point multiplication = ", np.dot(f1,f2))

f1 =
 [[5 5]
 [5 5]]

f2 =
 [[3 3]
 [3 3]]
point to point multiplication =  [[15 15]
 [15 15]]
point to point multiplication =  [[30 30]
 [30 30]]

In [31]:
#create a dictionary

StuDict={"Name": ["Aqsa","Esha", "Ayesha", "Ayra", "Arfa", "Afsa", "Abdul", "Saadia", "Abu Bakar","Atif"],
"ID": ["SID-1","SID-2", "SID-3", "SID-4", "SID-5","SID-6", "SID-7", "SID-8", "SID-9","SID-10"],
"Rol1_no": [1,2,3,4,5,6,7,8,9,10],
"Semester" : [7,7,7,7,6,6,6,5,8,8]}

StuDict

{'Name': ['Aqsa',
  'Esha',
  'Ayesha',
  'Ayra',
  'Arfa',
  'Afsa',
  'Abdul',
  'Saadia',
  'Abu Bakar',
  'Atif'],
 'ID': ['SID-1',
  'SID-2',
  'SID-3',
  'SID-4',
  'SID-5',
  'SID-6',
  'SID-7',
  'SID-8',
  'SID-9',
  'SID-10'],
 'Rol1_no': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 'Semester': [7, 7, 7, 7, 6, 6, 6, 5, 8, 8]}

In [34]:
#convert into data frames

import pandas as pd

data=pd.DataFrame (StuDict)

print(data)

print("\n\nThe data type of above given syntax is :",type (data))

        Name      ID  Rol1_no  Semester
0       Aqsa   SID-1        1         7
1       Esha   SID-2        2         7
2     Ayesha   SID-3        3         7
3       Ayra   SID-4        4         7
4       Arfa   SID-5        5         6
5       Afsa   SID-6        6         6
6      Abdul   SID-7        7         6
7     Saadia   SID-8        8         5
8  Abu Bakar   SID-9        9         8
9       Atif  SID-10       10         8


The data type of above given syntax is : <class 'pandas.DataFrame'>

In [4]:
import pandas as pd

StuDict = {
    "Name": ["Aqsa","Esha","Ayesha","Ayra","Arfa","Afsa","Abdul","Saadia","Abu Bakar","Atif"],

    "ID": ["SID-1","SID-2","SID-3","SID-4","SID-5",
           "SID-6","SID-7","SID-8","SID-9","SID-10"],

    "Rol1_no": [1,2,3,4,5,6,7,8,9,10],

    "Semester": [7,7,7,7,6,6,6,5,8,8]
}

data = pd.DataFrame(StuDict)

print(data.describe())

        Rol1_no   Semester
count  10.00000  10.000000
mean    5.50000   6.700000
std     3.02765   0.948683
min     1.00000   5.000000
25%     3.25000   6.000000
50%     5.50000   7.000000
75%     7.75000   7.000000
max    10.00000   8.000000

In [5]:
import pandas as pd

StuDict = {
    "Name": ["Aqsa","Esha","Ayesha","Ayra","Arfa","Afsa","Abdul","Saadia","Abu Bakar","Atif"],

    "ID": ["SID-1","SID-2","SID-3","SID-4","SID-5",
           "SID-6","SID-7","SID-8","SID-9","SID-10"],

    "Rol1_no": [1,2,3,4,5,6,7,8,9,10],

    "Semester": [7,7,7,7,6,6,6,5,8,8]
}

data = pd.DataFrame(StuDict)
print(data.head())

     Name     ID  Rol1_no  Semester
0    Aqsa  SID-1        1         7
1    Esha  SID-2        2         7
2  Ayesha  SID-3        3         7
3    Ayra  SID-4        4         7
4    Arfa  SID-5        5         6

In [6]:
import pandas as pd

StuDict = {
    "Name": ["Aqsa","Esha","Ayesha","Ayra","Arfa","Afsa","Abdul","Saadia","Abu Bakar","Atif"],

    "ID": ["SID-1","SID-2","SID-3","SID-4","SID-5",
           "SID-6","SID-7","SID-8","SID-9","SID-10"],

    "Rol1_no": [1,2,3,4,5,6,7,8,9,10],

    "Semester": [7,7,7,7,6,6,6,5,8,8]
}

data = pd.DataFrame(StuDict)
print(data.tail())

        Name      ID  Rol1_no  Semester
5       Afsa   SID-6        6         6
6      Abdul   SID-7        7         6
7     Saadia   SID-8        8         5
8  Abu Bakar   SID-9        9         8
9       Atif  SID-10       10         8

In [7]:
import pandas as pd

StuDict = {
    "Name": ["Aqsa","Esha","Ayesha","Ayra","Arfa","Afsa","Abdul","Saadia","Abu Bakar","Atif"],

    "ID": ["SID-1","SID-2","SID-3","SID-4","SID-5",
           "SID-6","SID-7","SID-8","SID-9","SID-10"],

    "Rol1_no": [1,2,3,4,5,6,7,8,9,10],

    "Semester": [7,7,7,7,6,6,6,5,8,8]
}

data = pd.DataFrame(StuDict)
print(data.info())

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      10 non-null     str
 1   ID        10 non-null     str
 2   Rol1_no   10 non-null     int64
 3   Semester  10 non-null     int64
dtypes: int64(2), str(2)
memory usage: 452.0 bytes
None

In [8]:
import pandas as pd

StuDict = {
    "Name": ["Aqsa","Esha","Ayesha","Ayra","Arfa","Afsa","Abdul","Saadia","Abu Bakar","Atif"],

    "ID": ["SID-1","SID-2","SID-3","SID-4","SID-5",
           "SID-6","SID-7","SID-8","SID-9","SID-10"],

    "Rol1_no": [1,2,3,4,5,6,7,8,9,10],

    "Semester": [7,7,7,7,6,6,6,5,8,8]
}

data = pd.DataFrame(StuDict)
data.to_csv('student.csv')

In [9]:
df = pd.read_csv('student.csv')
df

   Unnamed: 0       Name      ID  Rol1_no  Semester
0           0       Aqsa   SID-1        1         7
1           1       Esha   SID-2        2         7
2           2     Ayesha   SID-3        3         7
3           3       Ayra   SID-4        4         7
4           4       Arfa   SID-5        5         6
5           5       Afsa   SID-6        6         6
6           6      Abdul   SID-7        7         6
7           7     Saadia   SID-8        8         5
8           8  Abu Bakar   SID-9        9         8
9           9       Atif  SID-10       10         8

In [10]:
import pandas as pd
df = pd.read_csv('student.csv')

print(f"Describe Function \n {df.describe()}, \n head Function \n {df.head()} \n tail Function \n {df.tail()}")
print(f"\n info Function \n {df.info()}")

Describe Function
        Unnamed: 0   Rol1_no   Semester
count    10.00000  10.00000  10.000000
mean      4.50000   5.50000   6.700000
std       3.02765   3.02765   0.948683
min       0.00000   1.00000   5.000000
25%       2.25000   3.25000   6.000000
50%       4.50000   5.50000   7.000000
75%       6.75000   7.75000   7.000000
max       9.00000  10.00000   8.000000,
 head Function
    Unnamed: 0    Name     ID  Rol1_no  Semester
0           0    Aqsa  SID-1        1         7
1           1    Esha  SID-2        2         7
2           2  Ayesha  SID-3        3         7
3           3    Ayra  SID-4        4         7
4           4    Arfa  SID-5        5         6
 tail Function
    Unnamed: 0       Name      ID  Rol1_no  Semester
5           5       Afsa   SID-6        6         6
6           6      Abdul   SID-7        7         6
7           7     Saadia   SID-8        8         5
8           8  Abu Bakar   SID-9        9         8
9           9       Atif  SID-10       10         8
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  10 non-null     int64
 1   Name        10 non-null     str
 2   ID          10 non-null     str
 3   Rol1_no     10 non-null     int64
 4   Semester    10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 532.0 bytes

 info Function
 None

In [11]:
import pandas as pd

df['Name']

0         Aqsa
1         Esha
2       Ayesha
3         Ayra
4         Arfa
5         Afsa
6        Abdul
7       Saadia
8    Abu Bakar
9         Atif
Name: Name, dtype: str

In [12]:
df['Name'][0]

'Aqsa'

In [17]:
df.loc[0, 'Name'] = 'Saddam'
print(df)

   Unnamed: 0       Name      ID  Rol1_no  Semester
0           0     Saddam   SID-1        1         7
1           1       Esha   SID-2        2         7
2           2     Ayesha   SID-3        3         7
3           3       Ayra   SID-4        4         7
4           4       Arfa   SID-5        5         6
5           5       Afsa   SID-6        6         6
6           6      Abdul   SID-7        7         6
7           7     Saadia   SID-8        8         5
8           8  Abu Bakar   SID-9        9         8
9           9       Atif  SID-10       10         8

In [18]:
df.columns

Index(['Unnamed: 0', 'Name', 'ID', 'Rol1_no', 'Semester'], dtype='str')

In [19]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [20]:
import pandas as pd
import numpy as np

s = pd.Series(np.random.rand(50))
print(s)
print(f"Using dtype: {s.dtype}")
print(f"Using type: {type(s)}")
print(f"Using Shape: {s.shape}")

0     0.359989
1     0.307258
2     0.916212
3     0.011666
4     0.057098
5     0.687598
6     0.163324
7     0.094060
8     0.481405
9     0.142867
10    0.687153
11    0.460133
12    0.837332
13    0.215173
14    0.374928
15    0.846992
16    0.971961
17    0.391273
18    0.891769
19    0.836747
20    0.292115
21    0.592194
22    0.315896
23    0.285622
24    0.757067
25    0.165595
26    0.066409
27    0.796221
28    0.643789
29    0.073574
30    0.468906
31    0.056753
32    0.755605
33    0.622177
34    0.443968
35    0.201001
36    0.685156
37    0.796420
38    0.969382
39    0.771039
40    0.443589
41    0.999470
42    0.788696
43    0.617885
44    0.163976
45    0.319877
46    0.104855
47    0.346506
48    0.369736
49    0.935507
dtype: float64
Using dtype: float64
Using type: <class 'pandas.Series'>
Using Shape: (50,)

In [24]:
import pandas as pd
import numpy as np

dataf = pd.DataFrame(np.random.rand(50,5))
print(dataf)
print(f"Using dtype: {s.dtype}")
print(f"Using type: {type(s)}")
print(f"Using Shape: {s.shape}")

           0         1         2         3         4
0   0.924053  0.903683  0.160403  0.005564  0.166831
1   0.438343  0.387345  0.254219  0.407040  0.913458
2   0.928850  0.735367  0.464558  0.505011  0.538190
3   0.790299  0.773828  0.777899  0.216679  0.804781
4   0.313211  0.359362  0.812915  0.370194  0.475069
5   0.580541  0.686162  0.946736  0.774571  0.740499
6   0.345007  0.288892  0.689581  0.142579  0.205244
7   0.943066  0.197014  0.306710  0.567900  0.842238
8   0.656544  0.701388  0.314993  0.042614  0.983650
9   0.375825  0.079208  0.870397  0.521206  0.484824
10  0.888392  0.579570  0.784135  0.969225  0.628243
11  0.813573  0.590359  0.265845  0.905195  0.205449
12  0.736353  0.222499  0.436199  0.793165  0.582178
13  0.994995  0.567911  0.380015  0.757567  0.074528
14  0.448727  0.485607  0.122719  0.291472  0.706334
15  0.469303  0.856733  0.148168  0.322028  0.072412
16  0.600154  0.261119  0.428723  0.525746  0.989875
17  0.859142  0.166327  0.219340  0.142855  0.046265
18  0.071528  0.608301  0.661845  0.585818  0.685368
19  0.220655  0.011265  0.005450  0.179807  0.906482
20  0.050391  0.626993  0.524622  0.734364  0.770965
21  0.101332  0.631710  0.888131  0.496212  0.502967
22  0.336276  0.933361  0.001439  0.278775  0.971723
23  0.215148  0.517296  0.411272  0.215292  0.721473
24  0.724426  0.287737  0.226837  0.756815  0.566183
25  0.264179  0.001067  0.332293  0.399164  0.271197
26  0.077859  0.080451  0.728572  0.277344  0.383669
27  0.389782  0.882266  0.412301  0.925303  0.136052
28  0.681176  0.194840  0.126737  0.806287  0.138960
29  0.076397  0.057735  0.411399  0.858266  0.083496
30  0.151818  0.652993  0.599482  0.130379  0.841183
31  0.450094  0.281809  0.156051  0.185130  0.542014
32  0.187260  0.768413  0.855111  0.724108  0.913646
33  0.084749  0.961350  0.835063  0.704522  0.140032
34  0.991380  0.768891  0.062413  0.000772  0.200386
35  0.557752  0.895322  0.325197  0.784870  0.329352
36  0.350577  0.382027  0.837913  0.134607  0.339258
37  0.889291  0.886449  0.622081  0.596667  0.143288
38  0.257682  0.495908  0.192608  0.417133  0.480643
39  0.694908  0.697136  0.360071  0.175005  0.523237
40  0.455194  0.071026  0.074324  0.624022  0.863353
41  0.362934  0.819814  0.028359  0.622866  0.048524
42  0.194142  0.972929  0.820949  0.859580  0.712189
43  0.048824  0.563455  0.665814  0.329579  0.395864
44  0.768712  0.774691  0.895715  0.007747  0.195145
45  0.074723  0.862098  0.431908  0.102119  0.717532
46  0.014338  0.969752  0.596183  0.474803  0.880707
47  0.651704  0.098375  0.905537  0.915560  0.920638
48  0.603343  0.305238  0.658942  0.490797  0.559329
49  0.544416  0.992960  0.134206  0.636852  0.679127
Using dtype: float64
Using type: <class 'pandas.Series'>
Using Shape: (50,)

In [25]:
dataf.min()

0    0.014338
1    0.001067
2    0.001439
3    0.000772
4    0.046265
dtype: float64

In [26]:
dataf.max()

0    0.994995
1    0.992960
2    0.946736
3    0.969225
4    0.989875
dtype: float64

In [27]:
dataf.mean()

0    0.472987
1    0.537921
2    0.463448
3    0.473824
4    0.520481
dtype: float64

In [28]:
dataf[0].max()

np.float64(0.994994800136533)

In [29]:
d1 = dataf.to_numpy()
d1

array([[9.24053491e-01, 9.03682893e-01, 1.60403046e-01, 5.56413388e-03,
        1.66831096e-01],
       [4.38343338e-01, 3.87344639e-01, 2.54218900e-01, 4.07039619e-01,
        9.13458089e-01],
       [9.28850320e-01, 7.35366627e-01, 4.64558450e-01, 5.05010993e-01,
        5.38189729e-01],
       [7.90298541e-01, 7.73828433e-01, 7.77899423e-01, 2.16679176e-01,
        8.04781186e-01],
       [3.13210587e-01, 3.59361915e-01, 8.12915206e-01, 3.70194137e-01,
        4.75069427e-01],
       [5.80540863e-01, 6.86162162e-01, 9.46735744e-01, 7.74571151e-01,
        7.40499181e-01],
       [3.45007485e-01, 2.88891928e-01, 6.89581433e-01, 1.42579401e-01,
        2.05244285e-01],
       [9.43066310e-01, 1.97013815e-01, 3.06709918e-01, 5.67900075e-01,
        8.42238123e-01],
       [6.56543966e-01, 7.01387591e-01, 3.14993029e-01, 4.26140242e-02,
        9.83650422e-01],
       [3.75824806e-01, 7.92079890e-02, 8.70397284e-01, 5.21206179e-01,
        4.84824066e-01],
       [8.88392435e-01, 5.79570285e-01, 7.84134857e-01, 9.69224692e-01,
        6.28242532e-01],
       [8.13573311e-01, 5.90359053e-01, 2.65845164e-01, 9.05194938e-01,
        2.05449420e-01],
       [7.36352967e-01, 2.22499296e-01, 4.36198837e-01, 7.93164999e-01,
        5.82178362e-01],
       [9.94994800e-01, 5.67911281e-01, 3.80015030e-01, 7.57567234e-01,
        7.45276179e-02],
       [4.48727466e-01, 4.85606847e-01, 1.22719448e-01, 2.91472471e-01,
        7.06334073e-01],
       [4.69303453e-01, 8.56733477e-01, 1.48167524e-01, 3.22028164e-01,
        7.24116174e-02],
       [6.00154195e-01, 2.61119372e-01, 4.28723102e-01, 5.25746376e-01,
        9.89875384e-01],
       [8.59141631e-01, 1.66326555e-01, 2.19339860e-01, 1.42855113e-01,
        4.62645197e-02],
       [7.15280870e-02, 6.08301484e-01, 6.61844924e-01, 5.85818408e-01,
        6.85368187e-01],
       [2.20654946e-01, 1.12653161e-02, 5.44982871e-03, 1.79807171e-01,
        9.06481924e-01],
       [5.03905394e-02, 6.26993225e-01, 5.24621612e-01, 7.34364115e-01,
        7.70964634e-01],
       [1.01332318e-01, 6.31710394e-01, 8.88131304e-01, 4.96211928e-01,
        5.02967035e-01],
       [3.36276211e-01, 9.33361329e-01, 1.43927182e-03, 2.78775464e-01,
        9.71723172e-01],
       [2.15148393e-01, 5.17296470e-01, 4.11272212e-01, 2.15291998e-01,
        7.21472600e-01],
       [7.24426403e-01, 2.87736944e-01, 2.26837016e-01, 7.56814897e-01,
        5.66183137e-01],
       [2.64178895e-01, 1.06687335e-03, 3.32292794e-01, 3.99164493e-01,
        2.71197311e-01],
       [7.78593519e-02, 8.04514656e-02, 7.28571910e-01, 2.77343624e-01,
        3.83669228e-01],
       [3.89782387e-01, 8.82265646e-01, 4.12300874e-01, 9.25302788e-01,
        1.36052385e-01],
       [6.81176267e-01, 1.94840193e-01, 1.26736854e-01, 8.06287400e-01,
        1.38960497e-01],
       [7.63967087e-02, 5.77351585e-02, 4.11399037e-01, 8.58266108e-01,
        8.34964564e-02],
       [1.51818333e-01, 6.52993001e-01, 5.99481938e-01, 1.30378538e-01,
        8.41183154e-01],
       [4.50093550e-01, 2.81808986e-01, 1.56050820e-01, 1.85129809e-01,
        5.42013841e-01],
       [1.87260482e-01, 7.68412994e-01, 8.55111470e-01, 7.24107889e-01,
        9.13646457e-01],
       [8.47491824e-02, 9.61349552e-01, 8.35063064e-01, 7.04522039e-01,
        1.40031696e-01],
       [9.91379685e-01, 7.68891461e-01, 6.24129091e-02, 7.71904589e-04,
        2.00386409e-01],
       [5.57751763e-01, 8.95322023e-01, 3.25197456e-01, 7.84870111e-01,
        3.29352052e-01],
       [3.50577376e-01, 3.82026657e-01, 8.37912687e-01, 1.34606821e-01,
        3.39257682e-01],
       [8.89290864e-01, 8.86448902e-01, 6.22081185e-01, 5.96667068e-01,
        1.43288160e-01],
       [2.57681713e-01, 4.95907864e-01, 1.92607784e-01, 4.17132514e-01,
        4.80643478e-01],
       [6.94907938e-01, 6.97136013e-01, 3.60071361e-01, 1.75005299e-01,
        5.23237375e-01],
       [4.55194224e-01, 7.10257301e-02, 7.43239679e-02, 6.24022199e-01,
        8.63352609e-01],
       [3.62933687e-01, 8.19814035e-01, 2.83594245e-02, 6.22866015e-01,
        4.85239192e-02],
       [1.94142074e-01, 9.72928841e-01, 8.20948739e-01, 8.59579673e-01,
        7.12189205e-01],
       [4.88244879e-02, 5.63454612e-01, 6.65814000e-01, 3.29578680e-01,
        3.95864033e-01],
       [7.68712234e-01, 7.74691375e-01, 8.95714696e-01, 7.74654310e-03,
        1.95145008e-01],
       [7.47228688e-02, 8.62098010e-01, 4.31908462e-01, 1.02119396e-01,
        7.17531704e-01],
       [1.43376100e-02, 9.69751742e-01, 5.96183445e-01, 4.74803381e-01,
        8.80707442e-01],
       [6.51703536e-01, 9.83746347e-02, 9.05537280e-01, 9.15559879e-01,
        9.20638328e-01],
       [6.03343366e-01, 3.05237726e-01, 6.58941997e-01, 4.90797160e-01,
        5.59329151e-01],
       [5.44415673e-01, 9.92959631e-01, 1.34206317e-01, 6.36851577e-01,
        6.79126601e-01]])

In [30]:
d1.T

array([[9.24053491e-01, 4.38343338e-01, 9.28850320e-01, 7.90298541e-01,
        3.13210587e-01, 5.80540863e-01, 3.45007485e-01, 9.43066310e-01,
        6.56543966e-01, 3.75824806e-01, 8.88392435e-01, 8.13573311e-01,
        7.36352967e-01, 9.94994800e-01, 4.48727466e-01, 4.69303453e-01,
        6.00154195e-01, 8.59141631e-01, 7.15280870e-02, 2.20654946e-01,
        5.03905394e-02, 1.01332318e-01, 3.36276211e-01, 2.15148393e-01,
        7.24426403e-01, 2.64178895e-01, 7.78593519e-02, 3.89782387e-01,
        6.81176267e-01, 7.63967087e-02, 1.51818333e-01, 4.50093550e-01,
        1.87260482e-01, 8.47491824e-02, 9.91379685e-01, 5.57751763e-01,
        3.50577376e-01, 8.89290864e-01, 2.57681713e-01, 6.94907938e-01,
        4.55194224e-01, 3.62933687e-01, 1.94142074e-01, 4.88244879e-02,
        7.68712234e-01, 7.47228688e-02, 1.43376100e-02, 6.51703536e-01,
        6.03343366e-01, 5.44415673e-01],
       [9.03682893e-01, 3.87344639e-01, 7.35366627e-01, 7.73828433e-01,
        3.59361915e-01, 6.86162162e-01, 2.88891928e-01, 1.97013815e-01,
        7.01387591e-01, 7.92079890e-02, 5.79570285e-01, 5.90359053e-01,
        2.22499296e-01, 5.67911281e-01, 4.85606847e-01, 8.56733477e-01,
        2.61119372e-01, 1.66326555e-01, 6.08301484e-01, 1.12653161e-02,
        6.26993225e-01, 6.31710394e-01, 9.33361329e-01, 5.17296470e-01,
        2.87736944e-01, 1.06687335e-03, 8.04514656e-02, 8.82265646e-01,
        1.94840193e-01, 5.77351585e-02, 6.52993001e-01, 2.81808986e-01,
        7.68412994e-01, 9.61349552e-01, 7.68891461e-01, 8.95322023e-01,
        3.82026657e-01, 8.86448902e-01, 4.95907864e-01, 6.97136013e-01,
        7.10257301e-02, 8.19814035e-01, 9.72928841e-01, 5.63454612e-01,
        7.74691375e-01, 8.62098010e-01, 9.69751742e-01, 9.83746347e-02,
        3.05237726e-01, 9.92959631e-01],
       [1.60403046e-01, 2.54218900e-01, 4.64558450e-01, 7.77899423e-01,
        8.12915206e-01, 9.46735744e-01, 6.89581433e-01, 3.06709918e-01,
        3.14993029e-01, 8.70397284e-01, 7.84134857e-01, 2.65845164e-01,
        4.36198837e-01, 3.80015030e-01, 1.22719448e-01, 1.48167524e-01,
        4.28723102e-01, 2.19339860e-01, 6.61844924e-01, 5.44982871e-03,
        5.24621612e-01, 8.88131304e-01, 1.43927182e-03, 4.11272212e-01,
        2.26837016e-01, 3.32292794e-01, 7.28571910e-01, 4.12300874e-01,
        1.26736854e-01, 4.11399037e-01, 5.99481938e-01, 1.56050820e-01,
        8.55111470e-01, 8.35063064e-01, 6.24129091e-02, 3.25197456e-01,
        8.37912687e-01, 6.22081185e-01, 1.92607784e-01, 3.60071361e-01,
        7.43239679e-02, 2.83594245e-02, 8.20948739e-01, 6.65814000e-01,
        8.95714696e-01, 4.31908462e-01, 5.96183445e-01, 9.05537280e-01,
        6.58941997e-01, 1.34206317e-01],
       [5.56413388e-03, 4.07039619e-01, 5.05010993e-01, 2.16679176e-01,
        3.70194137e-01, 7.74571151e-01, 1.42579401e-01, 5.67900075e-01,
        4.26140242e-02, 5.21206179e-01, 9.69224692e-01, 9.05194938e-01,
        7.93164999e-01, 7.57567234e-01, 2.91472471e-01, 3.22028164e-01,
        5.25746376e-01, 1.42855113e-01, 5.85818408e-01, 1.79807171e-01,
        7.34364115e-01, 4.96211928e-01, 2.78775464e-01, 2.15291998e-01,
        7.56814897e-01, 3.99164493e-01, 2.77343624e-01, 9.25302788e-01,
        8.06287400e-01, 8.58266108e-01, 1.30378538e-01, 1.85129809e-01,
        7.24107889e-01, 7.04522039e-01, 7.71904589e-04, 7.84870111e-01,
        1.34606821e-01, 5.96667068e-01, 4.17132514e-01, 1.75005299e-01,
        6.24022199e-01, 6.22866015e-01, 8.59579673e-01, 3.29578680e-01,
        7.74654310e-03, 1.02119396e-01, 4.74803381e-01, 9.15559879e-01,
        4.90797160e-01, 6.36851577e-01],
       [1.66831096e-01, 9.13458089e-01, 5.38189729e-01, 8.04781186e-01,
        4.75069427e-01, 7.40499181e-01, 2.05244285e-01, 8.42238123e-01,
        9.83650422e-01, 4.84824066e-01, 6.28242532e-01, 2.05449420e-01,
        5.82178362e-01, 7.45276179e-02, 7.06334073e-01, 7.24116174e-02,
        9.89875384e-01, 4.62645197e-02, 6.85368187e-01, 9.06481924e-01,
        7.70964634e-01, 5.02967035e-01, 9.71723172e-01, 7.21472600e-01,
        5.66183137e-01, 2.71197311e-01, 3.83669228e-01, 1.36052385e-01,
        1.38960497e-01, 8.34964564e-02, 8.41183154e-01, 5.42013841e-01,
        9.13646457e-01, 1.40031696e-01, 2.00386409e-01, 3.29352052e-01,
        3.39257682e-01, 1.43288160e-01, 4.80643478e-01, 5.23237375e-01,
        8.63352609e-01, 4.85239192e-02, 7.12189205e-01, 3.95864033e-01,
        1.95145008e-01, 7.17531704e-01, 8.80707442e-01, 9.20638328e-01,
        5.59329151e-01, 6.79126601e-01]])

In [31]:
dataf.columns = ['A', 'B', 'C', 'D', 'E']
dataf

           A         B         C         D         E
0   0.924053  0.903683  0.160403  0.005564  0.166831
1   0.438343  0.387345  0.254219  0.407040  0.913458
2   0.928850  0.735367  0.464558  0.505011  0.538190
3   0.790299  0.773828  0.777899  0.216679  0.804781
4   0.313211  0.359362  0.812915  0.370194  0.475069
5   0.580541  0.686162  0.946736  0.774571  0.740499
6   0.345007  0.288892  0.689581  0.142579  0.205244
7   0.943066  0.197014  0.306710  0.567900  0.842238
8   0.656544  0.701388  0.314993  0.042614  0.983650
9   0.375825  0.079208  0.870397  0.521206  0.484824
10  0.888392  0.579570  0.784135  0.969225  0.628243
11  0.813573  0.590359  0.265845  0.905195  0.205449
12  0.736353  0.222499  0.436199  0.793165  0.582178
13  0.994995  0.567911  0.380015  0.757567  0.074528
14  0.448727  0.485607  0.122719  0.291472  0.706334
15  0.469303  0.856733  0.148168  0.322028  0.072412
16  0.600154  0.261119  0.428723  0.525746  0.989875
17  0.859142  0.166327  0.219340  0.142855  0.046265
18  0.071528  0.608301  0.661845  0.585818  0.685368
19  0.220655  0.011265  0.005450  0.179807  0.906482
20  0.050391  0.626993  0.524622  0.734364  0.770965
21  0.101332  0.631710  0.888131  0.496212  0.502967
22  0.336276  0.933361  0.001439  0.278775  0.971723
23  0.215148  0.517296  0.411272  0.215292  0.721473
24  0.724426  0.287737  0.226837  0.756815  0.566183
25  0.264179  0.001067  0.332293  0.399164  0.271197
26  0.077859  0.080451  0.728572  0.277344  0.383669
27  0.389782  0.882266  0.412301  0.925303  0.136052
28  0.681176  0.194840  0.126737  0.806287  0.138960
29  0.076397  0.057735  0.411399  0.858266  0.083496
30  0.151818  0.652993  0.599482  0.130379  0.841183
31  0.450094  0.281809  0.156051  0.185130  0.542014
32  0.187260  0.768413  0.855111  0.724108  0.913646
33  0.084749  0.961350  0.835063  0.704522  0.140032
34  0.991380  0.768891  0.062413  0.000772  0.200386
35  0.557752  0.895322  0.325197  0.784870  0.329352
36  0.350577  0.382027  0.837913  0.134607  0.339258
37  0.889291  0.886449  0.622081  0.596667  0.143288
38  0.257682  0.495908  0.192608  0.417133  0.480643
39  0.694908  0.697136  0.360071  0.175005  0.523237
40  0.455194  0.071026  0.074324  0.624022  0.863353
41  0.362934  0.819814  0.028359  0.622866  0.048524
42  0.194142  0.972929  0.820949  0.859580  0.712189
43  0.048824  0.563455  0.665814  0.329579  0.395864
44  0.768712  0.774691  0.895715  0.007747  0.195145
45  0.074723  0.862098  0.431908  0.102119  0.717532
46  0.014338  0.969752  0.596183  0.474803  0.880707
47  0.651704  0.098375  0.905537  0.915560  0.920638
48  0.603343  0.305238  0.658942  0.490797  0.559329
49  0.544416  0.992960  0.134206  0.636852  0.679127

In [32]:
dataf[['B', 'C']]

           B         C
0   0.903683  0.160403
1   0.387345  0.254219
2   0.735367  0.464558
3   0.773828  0.777899
4   0.359362  0.812915
5   0.686162  0.946736
6   0.288892  0.689581
7   0.197014  0.306710
8   0.701388  0.314993
9   0.079208  0.870397
10  0.579570  0.784135
11  0.590359  0.265845
12  0.222499  0.436199
13  0.567911  0.380015
14  0.485607  0.122719
15  0.856733  0.148168
16  0.261119  0.428723
17  0.166327  0.219340
18  0.608301  0.661845
19  0.011265  0.005450
20  0.626993  0.524622
21  0.631710  0.888131
22  0.933361  0.001439
23  0.517296  0.411272
24  0.287737  0.226837
25  0.001067  0.332293
26  0.080451  0.728572
27  0.882266  0.412301
28  0.194840  0.126737
29  0.057735  0.411399
30  0.652993  0.599482
31  0.281809  0.156051
32  0.768413  0.855111
33  0.961350  0.835063
34  0.768891  0.062413
35  0.895322  0.325197
36  0.382027  0.837913
37  0.886449  0.622081
38  0.495908  0.192608
39  0.697136  0.360071
40  0.071026  0.074324
41  0.819814  0.028359
42  0.972929  0.820949
43  0.563455  0.665814
44  0.774691  0.895715
45  0.862098  0.431908
46  0.969752  0.596183
47  0.098375  0.905537
48  0.305238  0.658942
49  0.992960  0.134206

In [33]:
dataf.iloc[:, 0:2]   # : means all rows and 0:2 means cloumns till 2

           A         B
0   0.924053  0.903683
1   0.438343  0.387345
2   0.928850  0.735367
3   0.790299  0.773828
4   0.313211  0.359362
5   0.580541  0.686162
6   0.345007  0.288892
7   0.943066  0.197014
8   0.656544  0.701388
9   0.375825  0.079208
10  0.888392  0.579570
11  0.813573  0.590359
12  0.736353  0.222499
13  0.994995  0.567911
14  0.448727  0.485607
15  0.469303  0.856733
16  0.600154  0.261119
17  0.859142  0.166327
18  0.071528  0.608301
19  0.220655  0.011265
20  0.050391  0.626993
21  0.101332  0.631710
22  0.336276  0.933361
23  0.215148  0.517296
24  0.724426  0.287737
25  0.264179  0.001067
26  0.077859  0.080451
27  0.389782  0.882266
28  0.681176  0.194840
29  0.076397  0.057735
30  0.151818  0.652993
31  0.450094  0.281809
32  0.187260  0.768413
33  0.084749  0.961350
34  0.991380  0.768891
35  0.557752  0.895322
36  0.350577  0.382027
37  0.889291  0.886449
38  0.257682  0.495908
39  0.694908  0.697136
40  0.455194  0.071026
41  0.362934  0.819814
42  0.194142  0.972929
43  0.048824  0.563455
44  0.768712  0.774691
45  0.074723  0.862098
46  0.014338  0.969752
47  0.651704  0.098375
48  0.603343  0.305238
49  0.544416  0.992960

In [34]:
dataf.loc[:, 'A':'C'] # loc function use to specify the columns label or name

           A         B         C
0   0.924053  0.903683  0.160403
1   0.438343  0.387345  0.254219
2   0.928850  0.735367  0.464558
3   0.790299  0.773828  0.777899
4   0.313211  0.359362  0.812915
5   0.580541  0.686162  0.946736
6   0.345007  0.288892  0.689581
7   0.943066  0.197014  0.306710
8   0.656544  0.701388  0.314993
9   0.375825  0.079208  0.870397
10  0.888392  0.579570  0.784135
11  0.813573  0.590359  0.265845
12  0.736353  0.222499  0.436199
13  0.994995  0.567911  0.380015
14  0.448727  0.485607  0.122719
15  0.469303  0.856733  0.148168
16  0.600154  0.261119  0.428723
17  0.859142  0.166327  0.219340
18  0.071528  0.608301  0.661845
19  0.220655  0.011265  0.005450
20  0.050391  0.626993  0.524622
21  0.101332  0.631710  0.888131
22  0.336276  0.933361  0.001439
23  0.215148  0.517296  0.411272
24  0.724426  0.287737  0.226837
25  0.264179  0.001067  0.332293
26  0.077859  0.080451  0.728572
27  0.389782  0.882266  0.412301
28  0.681176  0.194840  0.126737
29  0.076397  0.057735  0.411399
30  0.151818  0.652993  0.599482
31  0.450094  0.281809  0.156051
32  0.187260  0.768413  0.855111
33  0.084749  0.961350  0.835063
34  0.991380  0.768891  0.062413
35  0.557752  0.895322  0.325197
36  0.350577  0.382027  0.837913
37  0.889291  0.886449  0.622081
38  0.257682  0.495908  0.192608
39  0.694908  0.697136  0.360071
40  0.455194  0.071026  0.074324
41  0.362934  0.819814  0.028359
42  0.194142  0.972929  0.820949
43  0.048824  0.563455  0.665814
44  0.768712  0.774691  0.895715
45  0.074723  0.862098  0.431908
46  0.014338  0.969752  0.596183
47  0.651704  0.098375  0.905537
48  0.603343  0.305238  0.658942
49  0.544416  0.992960  0.134206

In [35]:
dataf.iloc[0:12, 2:4]

           C         D
0   0.160403  0.005564
1   0.254219  0.407040
2   0.464558  0.505011
3   0.777899  0.216679
4   0.812915  0.370194
5   0.946736  0.774571
6   0.689581  0.142579
7   0.306710  0.567900
8   0.314993  0.042614
9   0.870397  0.521206
10  0.784135  0.969225
11  0.265845  0.905195